------------------------------------------------------------------------
------------------------------------------------------------------------
--  DESCRIPTION:
--  Oracle directory configuration file.
--  This file is automatically generated for the database
--  instance %ORACLE_SID% on %ORACLE_HOST%
--
--  USAGE:
--  $ export ORACLE_SID=%ORACLE_SID%
--  $ sqlplus "sys/<password> as sysdba" @%ORACLE_SID%_directories.sql
--  This will restore all states in the application if they already exist.
------------------------------------------------------------------------
-- Overview:
-- This script creates Oracle directory objects to file systems that are
-- accessable from the Oracle databases through the Oracle admin user.
-- The directory object names are:  %DIRECTORY_OBJECTS%
-- for the file system directories: %DIRECTORY_LOCATIONS%
-- User privileges are specified in the privileges.sql file
-- and are usually granted both READ and WRITE access.
------------------------------------------------------------------------
--whenever SQLERROR exit failure
--whenever OSERROR exit failure
set serveroutput on size 1000000;
set pagesize 0
set verify off
set feedback off
set pages 100

spool log/%ORACLE_SID%_directories.log

prompt Creating the following directory objects:
host for dir in "%DIRECTORY_LOCATIONS%"; do if [[ ! -d $dir ]]; then mkdir -p $dir; chmod 775 $dir; fi; done

declare
  v_sql             varchar2(1000);

  v_dir_objects     constant varchar2(2000):='%DIRECTORY_OBJECTS%';
  v_dir_object      varchar2(100);
  v_do_last_index   pls_integer:=1;
  v_do_next_index   pls_integer;

  v_dir_locations   constant varchar2(2000):='%DIRECTORY_LOCATIONS%';
  v_dir_location    varchar2(100);
  v_dl_last_index   pls_integer:=1;
  v_dl_next_index   pls_integer;

  cursor c_dirs(p_name in varchar2) is
    select owner, directory_name
      from sys.all_directories
     where upper(directory_name) = upper(p_name);
begin
  -- Step through space-delimited lists
  v_do_next_index:=instr(v_dir_objects,' ',1);
  v_dl_next_index:=instr(v_dir_locations,  ' ',1);


  while(v_do_last_index < length(v_dir_objects))loop
    if(v_do_next_index=0)then
      v_do_next_index:=length(v_dir_objects)+1;
      v_dl_next_index:=length(v_dir_locations)+1;
    end if;

    v_dir_object    :=trim(substr(v_dir_objects,    v_do_last_index,v_do_next_index-v_do_last_index));
    v_dir_location  :=trim(substr(v_dir_locations,  v_dl_last_index,v_dl_next_index-v_dl_last_index));

    v_do_last_index:=v_do_next_index+1;
    v_dl_last_index:=v_dl_next_index+1;

    -- Check if directory object exists, and if it does, drop it
    for c in c_dirs(v_dir_object)loop
      begin
        dbms_output.put_line('Dropping existing directory object ['||c.directory_name||']...');
        v_sql:='drop directory '||c.directory_name;
        dbms_output.put_line(v_sql);
        execute immediate v_sql;
        commit;
        dbms_output.put_line('Success.');
      exception
        when others then
          dbms_output.put_line('* Error ['||sqlcode||']. Message ['||sqlerrm||'] while attempting to drop directory object ['||c.directory_name||'].');
      end;
    end loop;

    -- Create directory
    begin
      dbms_output.put_line('Creating new directory object ['||v_dir_object||']...');
      v_sql:='create directory '||v_dir_object||' as '''||v_dir_location||'''';
      dbms_output.put_line(v_sql);
      execute immediate v_sql;
      dbms_output.put_line('Success.');
    exception
      when others then
        dbms_output.put_line('* Error ['||sqlcode||']. Message ['||sqlerrm||'] while attempting to create database link ['||v_dir_object||'].');
    end;

    -- Loop control
    v_do_next_index:=instr(v_dir_objects,  ' ',v_do_last_index);
    v_dl_next_index:=instr(v_dir_locations,' ',v_dl_last_index);

  end loop;
end;
/

spool off
exit
------------------------------------------------------------------------
-- end of file
------------------------------------------------------------------------
