------------------------------------------------------------------------
------------------------------------------------------------------------
--  DESCRIPTION:
--  Oracle function configuration file.
--  This file is automatically generated for the database
--  instance %ORACLE_SID% on %ORACLE_HOST%
--
--  USAGE:
--  USAGE:
--  $ export ORACLE_SID=%ORACLE_SID%
--  $ sqlplus "sys/<password> as sysdba" @%ORACLE_SID%_functions.sql
--  This will restore all states in the application if they already exist.
------------------------------------------------------------------------
whenever SQLERROR exit failure
whenever OSERROR exit failure
set serveroutput on size 1000000;
set pagesize 0
set verify off
set feedback off
set pages 100

connect / as sysdba
spool log/%ORACLE_SID%_functions.log

-- {{ ORAPPI_INSTALLATION_BEGIN }}


-- {{ ORAPPI_INSTALLATION_END }}

-- Compile new invalid objects
declare
  cursor c_object is
    select owner, object_name
      from sys.dba_objects
     where trim(object_type) = 'FUNCTION'
       and status = 'INVALID';
begin
  for c in c_object loop
    begin
      execute immediate 'alter function '||c.owner||'.'||c.object_name||' compile';
    exception
      when others then
        dbms_output.put_line('Warn: Compilation error in '||c.owner||'.'||c.object_name||'. It could be that some dependencies have not yet been satisfied. This should resolve itself near the end of the installation.');
    end;
  end loop;
exception
  when others then
    dbms_output.put_line(sqlerrm);
end;
/

spool off
disconnect
exit;

------------------------------------------------------------------------
-- end of file
------------------------------------------------------------------------
