------------------------------------------------------------------------
------------------------------------------------------------------------
--  DESCRIPTION:
--  Oracle initial job configuration file.
--  This file is automatically generated for the database
--  instance %ORACLE_SID% on %ORACLE_HOST%
--
--  USAGE:
--  $ export ORACLE_SID=%ORACLE_SID%
--  $ sqlplus "sys/<password> as sysdba" @%ORACLE_SID%_jobs.sql
--  This will restore all states in the application if they already exist.
------------------------------------------------------------------------
whenever SQLERROR exit failure
whenever OSERROR exit failure
set serveroutput on size 1000000;
set pagesize 0
set verify off
set feedback off
set pages 100

connect / as sysdba
spool log/%ORACLE_SID%_jobs.log

-- Creates or Replaces JOB
-- Usage:
-- prompt Scheduler FSM every 30 seconds
-- exec submit_job('utl.schedule.fsm',sysdate,'sysdate+30/(24*60*60)');
create or replace procedure submit_job(
  p_proc in varchar2,               -- Procedure text
  p_start in date,                  -- When first due
  p_interval in varchar2)           -- Interval
as
  v_job number;
  cursor c_jobs(p_proc in varchar2) is
  select job, what
    from sys.dba_jobs
   where lower(what) like '% '||lower(p_proc)||';%';
begin
  -- Remove existing job
  for c in c_jobs(p_proc) loop
    begin
      dbms_job.remove(c.job);
    exception
      when others then
        dbms_output.put_line(sqlerrm);
        dbms_output.put_line('Could not remove job '||c.job||': '||c.what);
    end;
  end loop;

  -- Add new job
  dbms_job.submit(v_job,'begin '||p_proc||'; end;',p_start,p_interval,true);
  if(v_job is null)then
    raise program_error;
  end if;
  dbms_output.put_line('Submitted job will run for the first time at '||to_char(p_start,'HH24:MI:SS DDMMMYYYY')||'.');
  commit;
exception
  when others then
    dbms_output.put_line('The following job could not be submitted to DBMS_JOB:');
    dbms_output.put_line('begin '||p_proc||'; end;');
end;
/

-- {{ ORAPPI_INSTALLATION_BEGIN }}


-- {{ ORAPPI_INSTALLATION_END }}

drop procedure submit_job;

spool off
disconnect
exit;

------------------------------------------------------------------------
-- end of file
------------------------------------------------------------------------
