-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
--  DESCRIPTION:
--  Oracle Library configuration file. This file is automatically generated.
--  It has been set up to run on the database instance %ORACLE_SID%
--  on host %ORACLE_HOST%
--
--  USAGE:
--  $ export ORACLE_SID=%ORACLE_SID%
--  $ sqlplus "sys/<password> as sysdba" @%ORACLE_SID%_libraries.sql
--  This will restore the objects in the application if they already exist.
-------------------------------------------------------------------------------
whenever SQLERROR exit failure
whenever OSERROR exit failure
set serveroutput on size 1000000;
set pagesize 0
set verify off
set feedback off
set pages 100

connect / as sysdba
spool log/%ORACLE_SID%_libraries.log

-- {{ ORAPPI_INSTALLATION_BEGIN }}


-- {{ ORAPPI_INSTALLATION_END }}

spool off
disconnect
exit;

-------------------------------------------------------------------------------
-- end of file
-------------------------------------------------------------------------------
