------------------------------------------------------------------------
------------------------------------------------------------------------
--  DESCRIPTION:
--  Oracle database configuration file
--  This file is automatically generated using tools.
--
--  USAGE:
--  sqlplus /nolog @%ORACLE_SID%_tablespaces.sql
------------------------------------------------------------------------

-- TODO: Check that the user does not already exist before creating user,
-- otherwize the script bombs out.
-- TODO: Figure out a nice way of mapping Table creation scripts to
-- table spaces with difference names on the target system.
--   Or just simply say that the target tablespace names should be the same
--   as those on the source system.


--whenever SQLERROR exit failure
--whenever OSERROR exit failure
set serveroutput on size 1000000;
set pagesize 0
set verify off
set feedback off
set pages 100

connect / as sysdba
spool log/%ORACLE_SID%_tablespaces.log


prompt Ignore errors if the tablespace already exist:


-- Creating temp rollback segment
create rollback segment r0
storage (
  initial 16K
  next 16K
  minextents 2
  maxextents 20
) tablespace SYSTEM;
alter rollback segment r0 online;

-- Creating Rollback tablespace
create tablespace RBS
datafile '%ORACLE_DATA%/%ORACLE_SID%_RBS.dbf' size 20M
autoextend on next 10M
default storage (
        initial 5M
        next 5M
        minextents 5
        maxextents unlimited
        pctincrease 0
);

-- Creating Temp tablespace
-- Not required - done during database creation
--create temporary tablespace TEMP
--tempfile '%ORACLE_DATA%/%ORACLE_SID%_temp.dbf' size 20M EXTENT
--MANAGEMENT LOCAL;
--alter database tempfile '%ORACLE_DATA%/%ORACLE_SID%_temp.dbf'
--autoextend on next 10M;

-- Creating Rollback Segments
create rollback segment R01 tablespace RBS;
alter rollback segment R01 online;

create rollback segment R02 tablespace RBS;
alter rollback segment R02 online;

create rollback segment R03 tablespace RBS;
alter rollback segment R03 online;

create rollback segment R04 tablespace RBS;
alter rollback segment R04 online;

-- Not required - done during database creation
--prompt Create tablespace for SYSTEM
--CREATE TABLESPACE SYSTEM DATAFILE '%ORACLE_DATA%/%ORACLE_SID%_system.dbf' size 10M extent MANAGEMENT LOCAL --AUTOALLOCATE;
--ALTER DATABASE datafile '%ORACLE_DATA%/%ORACLE_SID%_system.dbf' autoextend on next 10M;


prompt Create tablespace for USERS
CREATE TABLESPACE USERS DATAFILE '%ORACLE_DATA%/%ORACLE_SID%_users.dbf' size 10M extent MANAGEMENT LOCAL AUTOALLOCATE;
ALTER DATABASE datafile '%ORACLE_DATA%/%ORACLE_SID%_users.dbf' autoextend on next 10M;

prompt Application tablespaces
create tablespace app01 logging datafile '%ORACLE_DATA%/%ORACLE_SID%_app01.dbf' size 10M extent MANAGEMENT LOCAL AUTOALLOCATE;
ALTER DATABASE datafile '%ORACLE_DATA%/%ORACLE_SID%_app01.dbf' autoextend on next 10M;

-- Note: Optimal tablespace size = required size + 64K
-- TODO: Make subpartion disk spaces

-- {{ ORAPPI_INSTALLATION_BEGIN }}


-- {{ ORAPPI_INSTALLATION_END }}


prompt Drop temp rollback segment
alter rollback segment r0 OFFLINE;
drop rollback segment r0;

spool off
disconnect
exit;

------------------------------------------------------------------------
-- end of file
------------------------------------------------------------------------
