------------------------------------------------------------------------
------------------------------------------------------------------------
--  DESCRIPTION:
--  Oracle application uninstallation file.
--  This file is automatically generated for the database
--  instance %ORACLE_SID% on %ORACLE_HOST%
--  This will delete the following schemas from the database:
--  %APPLICATION_SCHEMAS%
--
--  WARNING:
--  This will delete all non-system schemas, tables, packages etc from this
--  database instance. Only use this prior to performing a completely new
--  application installation over this database
--
--  USAGE:
--  $ export ORACLE_SID=%ORACLE_SID%
--  $ sqlplus /nolog @%ORACLE_SID%_uninstall.sql
------------------------------------------------------------------------
whenever SQLERROR exit failure
whenever OSERROR exit failure
set serveroutput on size 1000000;
set pagesize 0
set verify off
set feedback off
set pages 100

connect / as sysdba
spool log/%ORACLE_SID%_uninstall.log

-- Ensure that logged in user is SYS AS SYSDBA
declare
  v_user  varchar2(30);
  v_isdba varchar2(10);
begin
  select user, sys_context('userenv','isdba')
    into v_user,v_isdba
    from dual;
  if(user<>'SYS' or v_isdba<>'TRUE')then
    dbms_output.put_line('You are currently logged in as user '||v_user);
    if(v_isdba<>'TRUE')then
      dbms_output.put_line('with no SYSTEM DBA rights.');
    end if;
    dbms_output.put_line('**********************************************');
    dbms_output.put_line('* Please log in again as user SYS AS SYSDBA. *');
    dbms_output.put_line('**********************************************');
    raise PROGRAM_ERROR;
  else
    dbms_output.put_line('You are currently logged on as user '||v_user||' as SYSDBA.');
  end if;
end;
/

prompt ================================================================================
prompt WARNING: Only proceed if you want to remove all traces of the appplication
prompt from the %ORACLE_SID% database. The following schemas will be removed:
prompt %APPLICATION_SCHEMAS%
prompt Press RETURN to continue or press CTRL-C to abort.
prompt ================================================================================
pause

-- Show logged on users
prompt Checking for users still connected:
column logged_on_users form a75 heading "Logged on Oracle users:"
select 'User '||v.osuser||' using schema '||v.username||' is still connected.' as logged_on_users
  from sys.v_$session v,
       sys.dba_users u
 where v.username = u.username
   and u.username in ('%APPLICATION_SCHEMAS%')
   and v.status <> 'KILLED';

-- Kill user sessions
prompt Any open user sessions will now be killed.
pause  Press RETURN to continue or press CTRL-C to abort.

declare
  cursor c_session is
    select v.osuser,v.username,v.sid,v.serial#,v.machine,v.status
      from sys.v_$session v,
           sys.dba_users u
     where v.username = u.username
       and u.username in ('%APPLICATION_SCHEMAS%')
       and v.status <> 'KILLED';
  v_sql  varchar2(100);
begin
  for c in c_session loop
    v_sql := 'alter system kill session '''||c.sid||','||c.serial#||'''';
    execute immediate v_sql;
  end loop;
exception
  when others then
    dbms_output.put_line('* Error killing an open user session.');
end;
/

-- Check for Zombie sessions that did not get killed
prompt Checking for Zombie sessions that did not get killed:
column logged_on_users form a75 heading "Zombie sessions:"
select 'User '||v.osuser||' using schema '||v.username||' has mutated into a Zombie.' as logged_on_users
  from sys.v_$session v,
       sys.dba_users u
 where v.username = u.username
   and u.username in ('%APPLICATION_SCHEMAS%')
   and v.status <> 'KILLED'
  order by v.username;

prompt ================================================================================
prompt Often, it takes a while to completely kill orphaned or locked sessions. This can
prompt affect the subsequent schema deletion operations. If there are still such zombie
prompt sessions displayed above, then you must manually clear them before proceeding.
prompt Failing that, wait for ORACLE to clear them in its own time.
prompt Or take your chances and simply continue.
prompt Press RETURN to continue or press CTRL-C to abort.
prompt ================================================================================
pause

--  Drop all production schemas and their database objects
column dropping format a75 heading "Summary"
select 'Number of application Schemas to be dropped: '||count(username) as dropping
  from sys.dba_users
 where username in ('%APPLICATION_SCHEMAS%')
   and username <> user
 order by 1;

column dropping format a75 heading "Schemas to be dropped"
prompt Dropping the following schemas and their database objects:
select username as dropping
  from sys.dba_users
 where username in ('%APPLICATION_SCHEMAS%')
   and username <> user
 order by 1;

prompt Dropping...
-- Drop Schemas
declare
  cursor c_user is
    select username
      from sys.dba_users
     where username in ('%APPLICATION_SCHEMAS%')
       and username <> user
     order by 1;
begin
  for c in c_user loop
    begin
      execute immediate 'drop user '||c.username||' cascade';
      dbms_output.put_line('Dropped schema '||c.username);
    exception
      when others then
        dbms_output.put_line('* Exception ['||sqlcode||'] when dropping schema '||c.username||'. Message ['||sqlerrm||']');
        dbms_output.put_line('You should attempt to manually delete this schema.');
    end;
  end loop;
  dbms_output.put_line('Done.');
exception
  when others then
    dbms_output.put_line(sqlerrm);
end;
/


spool off
quit;
------------------------------------------------------------------------
-- end of file
------------------------------------------------------------------------


