------------------------------------------------------------------------
------------------------------------------------------------------------
--  DESCRIPTION:
--  Oracle views configuration file.
--  This file is automatically generated for the database
--  instance %ORACLE_SID% on %ORACLE_HOST%
--
--  USAGE:
--  USAGE:
--  $ export ORACLE_SID=%ORACLE_SID%
--  $ sqlplus "sys/<password> as sysdba" @%ORACLE_SID%_views.sql
--  This will restore all states in the application if they already exist.
------------------------------------------------------------------------
whenever SQLERROR exit failure
whenever OSERROR exit failure
set serveroutput on size 1000000;
set pagesize 0
set verify off
set feedback off
set pages 100

connect / as sysdba
spool log/%ORACLE_SID%_views.log

-- {{ ORAPPI_INSTALLATION_BEGIN }}


-- {{ ORAPPI_INSTALLATION_END }}

spool off
disconnect
exit;

------------------------------------------------------------------------
-- end of file
------------------------------------------------------------------------
