#!/usr/bin/perl

# Usage:  OracleError2Insert.pl oraus.dat > error_codes.sql
#         where oraus.dat is generated by OracleError2FlatFile.pl.
#         Input file is in the format:
#         FACILITY|LANGUAGE|ERROR_CODE|SUBCODE|MESSAGE|CAUSE|ACTION
#         Adjust the construction of the insert statement to suit
#         the design of the target table.
while(<>){
  next if $.==1;
  chomp;
  s/'/''/g;

  s/\\"/"/g;
  s/\\n/\n        /g;
  split /\|/;
  @_[4]=~s/\n/'||chr(10)||\n'/g;
  @_[4]=~s/&/'||chr(38)||'/g;
  @_[5]=~s/\n/'||chr(10)||\n'/g;
  @_[5]=~s/&/'||chr(38)||'/g;
  @_[6]=~s/\n/'||chr(10)||\n'/g;
  @_[6]=~s/&/'||chr(38)||'/g;
  print <<EOF;
insert into utl.error_codes(ERROR_CODE,MESSAGE,EXPLANATION) values (
-@_[2],
'@_[4]',
'Cause:  @_[5]'||chr(10)||\n'Action: @_[6]');
EOF
}


